# CMake project running on a single platform.
name: Ubuntu 20.04 Build (LibTorch 2.2.2, CUDA 12.1.1) --

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  LIBTORCH_URL: https://download.pytorch.org/libtorch/cu126/libtorch-shared-with-deps-2.6.0%2Bcu126.zip
  CUDNN_URL: https://developer.download.nvidia.com/compute/cudnn/9.7.0/local_installers/cudnn-local-repo-ubuntu2004-9.7.0_1.0-1_amd64.deb

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.21
      id: cuda-toolkit-linux
      with:
        cuda: '12.6.3'
        method: 'network'
        sub-packages: '["nvcc", "nvtx", "nvrtc", "nvrtc-dev", "cudart"]'

    - name: Verify CUDA Toolkit Installation
      run: |
        echo "Installed cuda version is: ${{steps.cuda-toolkit-linux.outputs.cuda}}"
        echo "Cuda install location: ${{steps.cuda-toolkit-linux.outputs.CUDA_PATH}}"
        nvcc -V
        cmake --version

    - name: Add CUDA Toolkit Paths
      run: |
        echo "CUDAToolkit_ROOT=${{ steps.cuda-toolkit-linux.outputs.CUDA_PATH }}" >> $GITHUB_ENV

    - name: Download and Install LibTorch
      run: |
        curl -L ${{ env.LIBTORCH_URL }} --output libtorch.zip
        unzip -q libtorch.zip -d libtorch
        sudo apt update
        sudo apt install libtbb-dev ninja-build
        echo "LibTorch_ROOT=$PWD/libtorch/libtorch" >> $GITHUB_ENV

    - name: Download and Install cuDNN
      run: |
        curl -L ${{ env.CUDNN_URL }} --output cudnn-local-repo-ubuntu2004-9.7.0_1.0-1_amd64.deb
        sudo dpkg -i cudnn-local-repo-ubuntu2004-9.7.0_1.0-1_amd64.deb
        sudo cp /var/cudnn-local-repo-ubuntu2004-9.7.0/cudnn-*-keyring.gpg /usr/share/keyrings/
        sudo apt-get update
        sudo apt-get -y install cudnn-cuda-12

    - name: Configure CMake
      run: |
        cmake --preset linux-release -DCUDAToolkit_ROOT=${{ env.CUDAToolkit_ROOT }} -DTORCH_CUDA_ARCH_LIST="8.0 8.6 8.9 9.0" -DCMAKE_PREFIX_PATH=${{ env.LibTorch_ROOT }}

    - name: Build
      run: |
        cd ./build/linux-release/
        cmake --build . --config ${{ env.BUILD_TYPE }}
