# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Windows 2019 Build (LibTorch 2.2.2, CUDA 12.1.1)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  LIBTORCH_URL: https://download.pytorch.org/libtorch/cu121/libtorch-win-shared-with-deps-2.2.2%2Bcu121.zip
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Download and Install Ninja
      run: |
        Start-BitsTransfer -Source ${{ env.NINJA_URL }} -Destination "ninja-win.zip"
        Expand-Archive -Path "ninja-win.zip" -DestinationPath ninja
        ls ".\"
        ls ".\ninja\"
        echo "---"
        echo "$PWD\ninja"
        echo "$PWD\ninja" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "---"

    - name: Test Ninja
      run: |
        echo "---"
        [Environment]::GetEnvironmentVariable("Path", [System.EnvironmentVariableTarget]::Machine)
        echo "---"
        echo "$env:PATH"
        echo "$env:GITHUB_PATH"
        echo "---"
        ninja.exe --version
        echo "---"
        echo "---"
        echo "---"
        ninja --version

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit-windows
      with:
        cuda: '12.1.1'
        method: 'network'
        sub-packages: '["nvcc", "nvtx", "nvrtc", "nvrtc_dev", "cudart", "visual_studio_integration"]'
    
    - name: Verify CUDA Toolkit Installation
      run: |
        echo "Installed cuda version is: ${{steps.cuda-toolkit-windows.outputs.cuda}}"
        echo "Cuda install location: ${{steps.cuda-toolkit-windows.outputs.CUDA_PATH}}"
        nvcc -V
        cmake --version

    - name: Add CUDA Toolkit Paths
      run: |
        ls "${{ steps.cuda-toolkit-windows.outputs.CUDA_PATH }}"
        echo "---"
        ls "${{ steps.cuda-toolkit-windows.outputs.CUDA_PATH }}\bin"
        echo "---"
        ls "${{ steps.cuda-toolkit-windows.outputs.CUDA_PATH }}\lib\x64"
        echo "${{ steps.cuda-toolkit-windows.outputs.CUDA_PATH }}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "${{ steps.cuda-toolkit-windows.outputs.CUDA_PATH }}\lib\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "CUDAToolkit_ROOT=${{ steps.cuda-toolkit-windows.outputs.CUDA_PATH }}" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV

    - name: Download and Install LibTorch
      run: |
        Start-BitsTransfer -Source ${{ env.LIBTORCH_URL }} -Destination libtorch.zip
        Expand-Archive -Path libtorch.zip -DestinationPath libtorch
        echo "LibTorch_ROOT=$PWD\libtorch\libtorch" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV
        echo "$PWD\libtorch\libtorch\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Configure CMake
      run: |
        ninja --version
        echo "---"
        pwd
        dir
        cd "D:\a\PPO-LibTorch\PPO-LibTorch\"
        echo "---"
        pwd
        dir
        echo "---"
        cmake --preset x64-release -DCUDAToolkit_ROOT="${{ env.CUDAToolkit_ROOT }}" -DTORCH_CUDA_ARCH_LIST="8.0 8.6 8.9 9.0" -DCMAKE_PREFIX_PATH="${{ env.LibTorch_ROOT }}"

    - name: Build
      run: |
        cd .\build\x64-release\
        cmake --build . --config ${{ env.BUILD_TYPE }}
