# CMake project running on a single platform.
name: Windows 2019 Build (LibTorch 2.2.2, CUDA 11.8.0) --

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  LIBTORCH_URL: https://download.pytorch.org/libtorch/cu126/libtorch-win-shared-with-deps-2.6.0%2Bcu126.zip
  CUDNN_URL: https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/cudnn-windows-x86_64-9.7.1.26_cuda12-archive.zip

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.21
      id: cuda-toolkit-windows
      with:
        cuda: '12.6.3'
        method: 'network'
        sub-packages: '["nvcc", "nvtx", "nvrtc", "nvrtc_dev", "cudart", "cublas", "cublas_dev", "visual_studio_integration"]'

    - name: Test All Required Build Tools Function
      run: |
        echo "Installed cuda version is: ${{steps.cuda-toolkit-windows.outputs.cuda}}"
        echo "Cuda install location: ${{steps.cuda-toolkit-windows.outputs.CUDA_PATH}}"
        cl
        nvcc -V
        cmake --version
        ninja --version

    - name: Add CUDA Toolkit Paths
      run: |
        echo "CUDAToolkit_ROOT=${{ steps.cuda-toolkit-windows.outputs.CUDA_PATH }}" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV

    - name: Download and Install LibTorch
      run: |
        Start-BitsTransfer -Source ${{ env.LIBTORCH_URL }} -Destination libtorch.zip
        Expand-Archive -Path libtorch.zip -DestinationPath libtorch
        echo "LibTorch_ROOT=$PWD\libtorch\libtorch" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV

    - name: Download and Install cuDNN
      run: |
        Start-BitsTransfer -Source ${{ env.CUDNN_URL }} -Destination cudnn.zip
        Expand-Archive -Path cudnn.zip -DestinationPath cudnn
        $innerFolder = Get-ChildItem -Path cudnn | Where-Object { $_.PSIsContainer } | Select-Object -First 1
        if ($innerFolder) {
          Rename-Item -Path $innerFolder.FullName -NewName "cudnn"
        }
        echo "CUDNN_ROOT_DIR=$PWD\cudnn\cudnn" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV

    - name: Configure CMake
      run: |
        cmake --preset x64-release -DCUDAToolkit_ROOT="${{ env.CUDAToolkit_ROOT }}" -DCMAKE_PREFIX_PATH="${{ env.LibTorch_ROOT }}" -DCUDNN_ROOT_DIR="${{ env.CUDNN_ROOT_DIR }}"

    - name: Build
      run: |
        cd .\build\x64-release\
        cmake --build . --config ${{ env.BUILD_TYPE }}

    - name: Test Build
      run: |
        cd .\build\x64-release\
        .\CompilationChecker.exe
